### ISSUE TITLE
Comparing a vertical Rectangle at +180 and -180 is sometimes wrong

### ISSUE THREAD

**Issue by dsmiley** [spatial4j/spatial4j#85]
Rectangle.relate(Rectangle) reports INTERSECTS in this case when the actual result should be either DISJOINT or preferably whatever the Y dimension reports when it's WITHIN or CONTAINS | :

This fails:
assertRelation(WITHIN, ctx.makeRectangle(-180, -180, -10, 10), ctx.makeRectangle(180, 180, -30, 30));
The existing tests normalize rects, and so this wasn't found.

**Comment by akaus** [comment]
Do you know when this will be fixed?

**Comment by dsmiley** [comment]
No. This has fallen off my radar but thanks for prodding to remind me.  Presumably you hit this bug?

**Comment by akaus** [comment]
Thanks David for reply. we did hit this as a bug. Also, I am not sure if we should convert -180 to +180 For example, rectangle ((-180,90),(180,0)) is of width 360 wrapping x axis. But, if you treat -180 as +180 then the width will be 0 and you won't be able to capture any points except matching to Y axis. So, I was just wondering whether we should treat -180 and +180 differently or not?

**Comment by dsmiley** [comment]
I don't mean all longitudes by themselves should be converted; I just mean a rectangle's longitudes provided that they are both at the dateline.  As it is, it converts, say, +180 to -170 to become -180 to -170 (so that it doesn't cross the dateline).  @ryantxu do you have an opinion if +180 to +180 should be normalized to -170 to -170 -- if there would be problems?  I like that better than making the rectangle relation logic more complicated.

**Comment by ryantxu** [comment]
converting +-180 to +-170 seems a little problematic -- at least it should
be +-179.999

BUT i kinda fear the trickle down affects of the various gridding systems
-- at 180, it is on the border of everything, at 179.999 this would get
converted into a bunch more terms/cells

ryan

**Comment by dsmiley** [comment]
Converting +180 to +179.999 would cause shapes that used to intersect with -180 to now not, which I think is bad.  I'm doubtful there's a big implication on the Lucene spatial side, which is what you imply by terms/cells.

It seems like a small, fairly safe step, to normalize a vertical line rectangle (which is a degenerate case) on the dateline to be -180.  I can easily write tests that would show it still intersects with what we expect it to, such as a +170 to +180 rect.

Though the thing to be aware of with any normalization done is that a round-trip of reading an input shape to outputting it again will reflect normalization.  That's pretty much inescapable; probably not a 'problem' and we do some normalization already.

**Comment by akaus** [comment]
I think, we should not touch a rectangle which is wrapping around x axis such as (-180,0)(180,-90) but, when a rectangle has zero width with -180 as x coordinates such as (-180,0)(-180,-90) should be converted into (+180,0)(+180,-90).

**Comment by akaus** [comment]
Any comments David @dsmiley  or Ryan @ryantxu

**Comment by varsis** [comment]
I have a interesting idea, just thinking out loud here for this one, but what if you normalize any rect that falls on -180 or 180. Shift it over to 0 by adding 180. Forcing the model to be the same, just need to be careful of the 0,180 case. 0,-180

**Comment by dsmiley** [comment]
@varsis There is logic similar to what you're talking about; and _it works_ for this scenario:  https://github.com/spatial4j/spatial4j/blob/master/src/main/java/com/spatial4j/core/shape/impl/RectangleImpl.java#L247   (it adds 360) What doesn't work is the rectangle equality case:  https://github.com/spatial4j/spatial4j/blob/master/src/main/java/com/spatial4j/core/shape/impl/RectangleImpl.java#L217  since -180 isn't +180.  This could either be fixed by adding more logic to this method on that line, *or* by normalizing vertical line rectangles to be one or the other at construction.

@akaus  This is a minor quibble but if we normalize I don't believe we should normalize to +180; I think we should normalize to -180, since -180 is the beginning and it's common for various range detection code to be inclusive of the start boundary but exclusive of the end.

So I could go either way -- normalize vertical line rectangles to -180, or add extra logic to relate(rect) to deem longitude +/- 180 zero width as equal longitudinally.  I suppose the latter is nice in that we're not changing the input, which is what normalization does.  *Cool?*  I'll put up a patch with tests next week.

**Comment by akaus** [comment]
@dsmiley Latter sounds awesome. Thanks for input.

**Comment by dsmiley** [comment]
Look okay? https://github.com/spatial4j/spatial4j/compare/fix-vertical-rect-at-dateline

**Comment by akaus** [comment]
Thanks David!! It looks great!! I just ran the test case and it is working as expected.
